online2-wav-nnet2-latgen-faster --online=true --do-endpointing=false --config=exp/nnet2_online/nnet_a_gpu_online/conf/online_nnet2_decoding.conf --max-active=5000 --beam=14 --lattice-beam=6 --acoustic-scale=0.1 --word-symbol-table=exp/tri3b/graph/words.txt exp/nnet2_online/nnet_a_gpu_online/final.mdl exp/tri3b/graph/HCLG.fst ark:data/test/split30/nbravo/spk2utt "ark,s,cs:extract-segments scp,p:data/test/split30/nbravo/wav.scp data/test/split30/nbravo/segments ark:- |" "ark:|gzip -c > exp/nnet2_online/nnet_a_gpu_online/decode_test/lat.nbravo_5000_14_6.gz" && lattice-scale --inv-acoustic-scale=10 "ark:gunzip -c exp/nnet2_online/nnet_a_gpu_online/decode_test/lat.nbravo_5000_14_6.gz|" ark:- | lattice-add-penalty --word-ins-penalty=0.0 ark:- ark:- | lattice-best-path --word-symbol-table=exp/tri3b/graph/words.txt ark:- ark,t:exp/nnet2_online/nnet_a_gpu_online/decode_test/scoring/nbravo_5000_14_6.tra
----------
online2-wav-nnet2-latgen-faster --online=true --do-endpointing=false --config=exp/nnet2_online/nnet_a_gpu_online/conf/online_nnet2_decoding.conf --max-active=6000 --beam=14 --lattice-beam=6 --acoustic-scale=0.1 --word-symbol-table=exp/tri3b/graph/words.txt exp/nnet2_online/nnet_a_gpu_online/final.mdl exp/tri3b/graph/HCLG.fst ark:data/test/split30/nbravo/spk2utt "ark,s,cs:extract-segments scp,p:data/test/split30/nbravo/wav.scp data/test/split30/nbravo/segments ark:- |" "ark:|gzip -c > exp/nnet2_online/nnet_a_gpu_online/decode_test/lat.nbravo_6000_14_6.gz" && lattice-scale --inv-acoustic-scale=10 "ark:gunzip -c exp/nnet2_online/nnet_a_gpu_online/decode_test/lat.nbravo_6000_14_6.gz|" ark:- | lattice-add-penalty --word-ins-penalty=0.0 ark:- ark:- | lattice-best-path --word-symbol-table=exp/tri3b/graph/words.txt ark:- ark,t:exp/nnet2_online/nnet_a_gpu_online/decode_test/scoring/nbravo_6000_14_6.tra
----------
online2-wav-nnet2-latgen-faster --online=true --do-endpointing=false --config=exp/nnet2_online/nnet_a_gpu_online/conf/online_nnet2_decoding.conf --max-active=7000 --beam=14 --lattice-beam=6 --acoustic-scale=0.1 --word-symbol-table=exp/tri3b/graph/words.txt exp/nnet2_online/nnet_a_gpu_online/final.mdl exp/tri3b/graph/HCLG.fst ark:data/test/split30/nbravo/spk2utt "ark,s,cs:extract-segments scp,p:data/test/split30/nbravo/wav.scp data/test/split30/nbravo/segments ark:- |" "ark:|gzip -c > exp/nnet2_online/nnet_a_gpu_online/decode_test/lat.nbravo_7000_14_6.gz" && lattice-scale --inv-acoustic-scale=10 "ark:gunzip -c exp/nnet2_online/nnet_a_gpu_online/decode_test/lat.nbravo_7000_14_6.gz|" ark:- | lattice-add-penalty --word-ins-penalty=0.0 ark:- ark:- | lattice-best-path --word-symbol-table=exp/tri3b/graph/words.txt ark:- ark,t:exp/nnet2_online/nnet_a_gpu_online/decode_test/scoring/nbravo_7000_14_6.tra
----------
cat exp/nnet2_online/nnet_a_gpu_online/decode_test/scoring/nbravo_5000_14_6.tra | utils/int2sym.pl -f 2- exp/tri3b/graph/words.txt | sed s:\<UNK\>::g | compute-wer --text --mode=present ark:exp/nnet2_online/nnet_a_gpu_online/decode_test/scoring/test_filt.txt ark,p:- > exp/nnet2_online/nnet_a_gpu_online/decode_test/wer_nbravo_5000_14_6
----------
cat exp/nnet2_online/nnet_a_gpu_online/decode_test/scoring/nbravo_6000_14_6.tra | utils/int2sym.pl -f 2- exp/tri3b/graph/words.txt | sed s:\<UNK\>::g | compute-wer --text --mode=present ark:exp/nnet2_online/nnet_a_gpu_online/decode_test/scoring/test_filt.txt ark,p:- > exp/nnet2_online/nnet_a_gpu_online/decode_test/wer_nbravo_6000_14_6
----------
cat exp/nnet2_online/nnet_a_gpu_online/decode_test/scoring/nbravo_7000_14_6.tra | utils/int2sym.pl -f 2- exp/tri3b/graph/words.txt | sed s:\<UNK\>::g | compute-wer --text --mode=present ark:exp/nnet2_online/nnet_a_gpu_online/decode_test/scoring/test_filt.txt ark,p:- > exp/nnet2_online/nnet_a_gpu_online/decode_test/wer_nbravo_7000_14_6
----------
