rm exp/nnet2_online/nnet_a_gpu_online/decode_test/lat.1_*
rm exp/nnet2_online/nnet_a_gpu_online/decode_test/scoring/1_*
rm exp/nnet2_online/nnet_a_gpu_online/decode_test/wer_1_*
rm exp/nnet2_online/nnet_a_gpu_online/decode_test/*nbravo*
rm exp/nnet2_online/nnet_a_gpu_online/decode_test/scoring/*nbravo*
rm exp/nnet2_online/nnet_a_gpu_online/decode_test/*nbravo*
rm *.log
rm *ctl*
rm *.txt
